# Generated by Django 3.2.4 on 2021-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tokenapp', '0002_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
            ],
        ),
    ]
