# Generated by Django 3.2.4 on 2021-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tokenapp', '0003_currenttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('token', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('gr_no', models.IntegerField()),
                ('branch', models.CharField(max_length=10)),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('passout', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniCurrentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
            ],
        ),
    ]
